name = "LeanNiche"
version = "0.1.0"
description = "Advanced Deep Research Environment for Mathematics and Dynamical Systems"

# Main LeanNiche library with comprehensive source directory
[[_lean_lib]]
name = "LeanNiche"
srcDir = "src/lean"

# Main executable
[[lean_exe]]
name = "lean_niche"
root = "Main"
srcDir = "src/lean/core"

# Test suite executable
[[lean_exe]]
name = "test_suite"
root = "TestSuite"
srcDir = "src/tests"
