name = "LeanNiche"
version = "0.1.0"
description = "Advanced Deep Research Environment for Mathematics and Dynamical Systems"

[[_lean_lib]]
name = "LeanNiche"
srcDir = "src/lean/core"

[[lean_exe]]
name = "lean_niche"
root = "Main"
srcDir = "src/lean/core"

[[lean_exe]]
name = "test_suite"
root = "TestSuite"
srcDir = "src/tests"
